### ISSUE TITLE
How to  determine `-x`  for DASedit

### ISSUE THREAD

**Issue by mictadlo** [rrwick/DASCRUBBER-wrapper#3]
Hi,
How do you determine `-x`  for DASedit?

Thank you in advance.

Michal

**Comment by rrwick** [comment]
I had to look that one up [in the source code](https://github.com/thegenemyers/DASCRUBBER/blob/master/DASedit.c#L253). `-x` sets a minimum length for edited reads, which I assume means that reads smaller than this are filtered out.

I've never used the option myself, but if I did I would maybe set it to 1000, i.e. exclude reads less than a kilobase. But you should probably look at the distribution of read lengths in your input read set when considering such a threshold.

Ryan

**Comment by mictadlo** [comment]
Thank you.
