### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by mictadlo** [rrwick/DASCRUBBER-wrapper#4]
Hi,
it seems DASCRUBBER ( https://github.com/thegenemyers/DAMASKER/issues/10 ) got new tools to help to choose right arguments.

Thank you in advance.

Michal

**Comment by rrwick** [comment]
Thanks. I see that Gene recently changed some more things, with a recent commit titled 'pipeline overhaul'. So I should probably take a fresh look and make any necessary updates to my wrapper.

Ryan

**Comment by rrwick** [comment]
Okay, I've made the changes and I think this wrapper will now work for the current version of DASCRUBBER. Let me know if you have any issues!

Ryan
